

export default function EcommerceData() {
  return (
    [
        {
            status: "Sale",
            discount: "-40%",
            productImage: "/images/product1.png",
            title: "Solar Power Bank",
            price: "₦12,000",
            originalPrice: "₦20,000",
            colors: ["bg-orange-500", "bg-yellow-400", "bg-blue-500", "bg-black"],
          },
          {
            status: "Limited",
            discount: "-25%",
            productImage: "/images/product1.png",
            title: "Wireless Earbuds",
            price: "₦8,000",
            originalPrice: "₦10,500",
            colors: ["bg-gray-500", "bg-red-500", "bg-white", "bg-black"],
          },
          {
            status: "Sale",
            discount: "-60%",
            productImage: "/images/product1.png",
            title: "Bluetooth Speaker",
            price: "₦4,500",
            originalPrice: "₦11,000",
            colors: ["bg-green-500", "bg-blue-500", "bg-gray-400", "bg-black"],
          },
          {
            status: "New",
            discount: "-50%",
            productImage: "/images/product1.png",
            title: "Smart Water Bottle",
            price: "₦9,500",
            originalPrice: "₦19,000",
            colors: ["bg-cyan-500", "bg-blue-300", "bg-pink-400", "bg-black"],
          },
          {
            status: "Hot",
            discount: "-35%",
            productImage: "/images/product1.png",
            title: "4K Action Camera",
            price: "₦25,000",
            originalPrice: "₦38,500",
            colors: ["bg-red-600", "bg-yellow-500", "bg-gray-300", "bg-black"],
          },
          {
            status: "New",
            discount: "-20%",
            productImage: "/images/product1.png",
            title: "Smart Fitness Tracker",
            price: "₦18,000",
            originalPrice: "₦22,500",
            colors: ["bg-green-500", "bg-gray-500", "bg-blue-300", "bg-black"],
          },
          {
            status: "Limited",
            discount: "-45%",
            productImage: "/images/product1.png",
            title: "Portable Projector",
            price: "₦30,000",
            originalPrice: "₦55,000",
            colors: ["bg-yellow-400", "bg-green-300", "bg-blue-400", "bg-black"],
          },
          {
            status: "Sale",
            discount: "-50%",
            productImage: "/images/product1.png",
            title: "Smart Coffee Maker",
            price: "₦20,000",
            originalPrice: "₦40,000",
            colors: ["bg-brown-500", "bg-gray-300", "bg-red-500", "bg-black"],
          },
          {
            status: "New",
            discount: "-15%",
            productImage: "/images/product1.png",
            title: "AI-powered Vacuum Cleaner",
            price: "₦60,000",
            originalPrice: "₦70,500",
            colors: ["bg-black", "bg-blue-500", "bg-gray-400", "bg-white"],
          },
          {
            status: "Hot",
            discount: "-25%",
            productImage: "/images/product1.png",
            title: "Electric Skateboard",
            price: "₦75,000",
            originalPrice: "₦100,000",
            colors: ["bg-yellow-500", "bg-red-400", "bg-blue-500", "bg-black"],
          },
          {
            status: "Sale",
            discount: "-30%",
            productImage: "/images/product1.png",
            title: "Smart Doorbell",
            price: "₦10,500",
            originalPrice: "₦15,000",
            colors: ["bg-blue-500", "bg-gray-300", "bg-yellow-500", "bg-black"],
          },
          {
            status: "New",
            discount: "-35%",
            productImage: "/images/product1.png",
            title: "Smart Thermostat",
            price: "₦25,000",
            originalPrice: "₦38,000",
            colors: ["bg-gray-500", "bg-blue-500", "bg-black", "bg-white"],
          },
          {
            status: "Limited",
            discount: "-50%",
            productImage: "/images/product1.png",
            title: "Portable Air Conditioner",
            price: "₦55,000",
            originalPrice: "₦110,000",
            colors: ["bg-blue-500", "bg-gray-300", "bg-cyan-400", "bg-black"],
          },
          {
            status: "Hot",
            discount: "-10%",
            productImage: "/images/product1.png",
            title: "Robot Dog",
            price: "₦85,000",
            originalPrice: "₦95,000",
            colors: ["bg-gray-500", "bg-white", "bg-black", "bg-yellow-400"],
          },
          {
            status: "New",
            discount: "-45%",
            productImage: "/images/product1.png",
            title: "Smartwatch",
            price: "₦12,000",
            originalPrice: "₦22,000",
            colors: ["bg-green-500", "bg-blue-300", "bg-gray-300", "bg-black"],
          },
          {
            status: "Sale",
            discount: "-35%",
            productImage: "/images/product1.png",
            title: "Noise-Canceling Headphones",
            price: "₦32,000",
            originalPrice: "₦48,500",
            colors: ["bg-black", "bg-gray-500", "bg-blue-400", "bg-red-500"],
          },
          {
            status: "New",
            discount: "-20%",
            productImage: "/images/product1.png",
            title: "Wireless Charging Pad",
            price: "₦7,500",
            originalPrice: "₦9,500",
            colors: ["bg-blue-500", "bg-cyan-500", "bg-gray-300", "bg-black"],
          },
          {
            status: "Limited",
            discount: "-50%",
            productImage: "/images/product1.png",
            title: "Electric Kettle",
            price: "₦4,500",
            originalPrice: "₦9,000",
            colors: ["bg-gray-500", "bg-black", "bg-white", "bg-blue-500"],
          },
          {
            status: "Hot",
            discount: "-40%",
            productImage: "/images/product1.png",
            title: "Gaming Mouse",
            price: "₦10,000",
            originalPrice: "₦16,500",
            colors: ["bg-red-500", "bg-black", "bg-blue-500", "bg-gray-300"],
          },
          
    ]
  )
}
